% Build and open the Stage1 uniform ball-joint PD Simulink model.

init_stage1_ball_joint_pd_workspace;

model_name = "stage1_ball_joint_pd_uniform";
model_file = fullfile(script_dir, model_name + ".slx");

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

if isfile(model_file)
    load_system(model_file);
    Simulink.BlockDiagram.deleteContents(model_name);
else
    new_system(model_name);
end
load_system("simulink");

set_param(model_name, ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "dt_sim", ...
    "StopTime", "stop_time_s", ...
    "SignalLogging", "on");

init_callback = ...
    "evalin('base', 'run(fullfile(fileparts(get_param(''stage1_ball_joint_pd_uniform'', ''FileName'')), ''init_stage1_ball_joint_pd_workspace.m''))')";
set_param(model_name, ...
    "PostLoadFcn", init_callback, ...
    "InitFcn", init_callback);

add_model_blocks(model_name);
save_system(model_name, model_file);
open_system(model_name);

fprintf("Built and opened Simulink model: %s\n", model_file);
fprintf("Workspace source trace: %s\n", string(trace_csv_path));
fprintf("Default uniform gain: Kp = %.3g, Kd = %.3g, tau_v = %.3g, tau_max = %.3g, qdot_max = %.3g\n", ...
    Kp, Kd, tau_v, tau_max, qdot_max);

function add_model_blocks(model_name)
    add_inputs(model_name);
    add_plant(model_name);
    add_outputs(model_name);
    add_joint_display_subsystems(model_name);
    style_blocks(model_name);
    connect_blocks(model_name);
end

function add_inputs(model_name)
    add_block("simulink/Sources/From Workspace", model_name + "/q_desired", ...
        "VariableName", "q_desired_ts", ...
        "SampleTime", "dt_ctrl", ...
        "Position", [35, 70, 170, 100]);
    add_block("simulink/Sources/From Workspace", model_name + "/q_target_old", ...
        "VariableName", "q_target_old_ts", ...
        "SampleTime", "dt_ctrl", ...
        "Position", [35, 145, 170, 175]);
    add_block("simulink/Sources/From Workspace", model_name + "/q_actual_old", ...
        "VariableName", "q_actual_old_ts", ...
        "SampleTime", "dt_ctrl", ...
        "Position", [35, 220, 170, 250]);
    add_block("simulink/Sources/From Workspace", model_name + "/qdot_actual_old", ...
        "VariableName", "qdot_actual_old_ts", ...
        "SampleTime", "dt_ctrl", ...
        "Position", [35, 520, 170, 550]);
    add_block("simulink/Sources/From Workspace", model_name + "/qdot_cmd_old", ...
        "VariableName", "qdot_cmd_old_ts", ...
        "SampleTime", "dt_ctrl", ...
        "Position", [35, 595, 170, 625]);
end

function add_plant(model_name)
    add_block("simulink/Discontinuities/Saturation", model_name + "/Clamp q target", ...
        "UpperLimit", "q_upper", ...
        "LowerLimit", "q_lower", ...
        "Position", [245, 70, 365, 100]);
    add_block("simulink/Math Operations/Sum", model_name + "/q error", ...
        "Inputs", "+-", ...
        "Position", [430, 70, 455, 125]);
    add_block("simulink/Math Operations/Gain", model_name + "/Kp", ...
        "Gain", "Kp", ...
        "Position", [505, 70, 575, 110]);
    add_block("simulink/Math Operations/Gain", model_name + "/Kd", ...
        "Gain", "Kd", ...
        "Position", [505, 240, 575, 280]);
    add_block("simulink/Math Operations/Sum", model_name + "/PD torque", ...
        "Inputs", "+-", ...
        "Position", [635, 120, 665, 175]);
    add_block("simulink/Discontinuities/Saturation", model_name + "/Torque saturation", ...
        "UpperLimit", "tau_max", ...
        "LowerLimit", "-tau_max", ...
        "Position", [720, 125, 840, 165]);
    add_block("simulink/Math Operations/Gain", model_name + "/B damping", ...
        "Gain", "B_axis", ...
        "Position", [725, 240, 795, 280]);
    add_block("simulink/Sources/Constant", model_name + "/Load torque", ...
        "Value", "tau_load", ...
        "Position", [720, 315, 795, 345]);
    add_block("simulink/Math Operations/Sum", model_name + "/Acceleration numerator", ...
        "Inputs", "+--", ...
        "Position", [895, 180, 930, 255]);
    add_block("simulink/Math Operations/Gain", model_name + "/InvJ", ...
        "Gain", "1/J_axis", ...
        "Position", [980, 200, 1055, 240]);
    add_block("simulink/Discrete/Discrete-Time Integrator", model_name + "/qdot integrator", ...
        "InitialCondition", "zeros(1, 6)", ...
        "SampleTime", "dt_sim", ...
        "Position", [1110, 200, 1210, 240]);
    add_block("simulink/Discontinuities/Saturation", model_name + "/qdot saturation", ...
        "UpperLimit", "qdot_max", ...
        "LowerLimit", "-qdot_max", ...
        "Position", [1260, 200, 1375, 240]);
    add_block("simulink/Discrete/Discrete-Time Integrator", model_name + "/q integrator", ...
        "InitialCondition", "zeros(1, 6)", ...
        "SampleTime", "dt_sim", ...
        "Position", [1430, 200, 1530, 240]);
    add_block("simulink/Discontinuities/Saturation", model_name + "/q saturation", ...
        "UpperLimit", "q_upper", ...
        "LowerLimit", "q_lower", ...
        "Position", [1580, 200, 1695, 240]);
    add_block("simulink/Discrete/Discrete Transfer Fcn", model_name + "/qdot allocator LPF", ...
        "Numerator", "[alpha_v]", ...
        "Denominator", "[1 -(1-alpha_v)]", ...
        "SampleTime", "dt_ctrl", ...
        "Position", [1430, 320, 1570, 365]);
    add_block("simulink/Math Operations/Abs", model_name + "/Abs tau", ...
        "Position", [900, 85, 940, 125]);
    add_block("simulink/Logic and Bit Operations/Compare To Constant", model_name + "/tau saturation flag", ...
        "relop", ">=", ...
        "const", "0.98*tau_max", ...
        "Position", [985, 85, 1110, 125]);
end

function add_outputs(model_name)
    add_to_workspace(model_name, "q_target_new", [1810, 40, 1965, 70]);
    add_to_workspace(model_name, "q_sim_new", [1810, 85, 1965, 115]);
    add_to_workspace(model_name, "qdot_sim_new", [1810, 130, 1965, 160]);
    add_to_workspace(model_name, "qdot_alloc_new", [1810, 175, 1965, 205]);
    add_to_workspace(model_name, "tau_sim_new", [1810, 220, 1965, 250]);
    add_to_workspace(model_name, "tau_saturation_flag_new", [1810, 265, 1965, 295]);

    add_goto(model_name, "goto_q_desired", "q_desired_vec", [1810, 340, 1935, 370]);
    add_goto(model_name, "goto_q_target_old", "q_target_old_vec", [1810, 385, 1935, 415]);
    add_goto(model_name, "goto_q_actual_old", "q_actual_old_vec", [1810, 430, 1935, 460]);
    add_goto(model_name, "goto_qdot_actual_old", "qdot_actual_old_vec", [1810, 475, 1935, 505]);
    add_goto(model_name, "goto_qdot_cmd_old", "qdot_cmd_old_vec", [1810, 520, 1935, 550]);
    add_goto(model_name, "goto_q_target_new", "q_target_new_vec", [2015, 40, 2140, 70]);
    add_goto(model_name, "goto_q_sim_new", "q_sim_new_vec", [2015, 85, 2140, 115]);
    add_goto(model_name, "goto_qdot_sim_new", "qdot_sim_new_vec", [2015, 130, 2140, 160]);
    add_goto(model_name, "goto_qdot_alloc_new", "qdot_alloc_new_vec", [2015, 175, 2140, 205]);
    add_goto(model_name, "goto_tau_sim_new", "tau_sim_new_vec", [2015, 220, 2140, 250]);
end

function add_to_workspace(model_name, variable_name, position)
    add_block("simulink/Sinks/To Workspace", model_name + "/" + variable_name, ...
        "VariableName", variable_name, ...
        "SaveFormat", "Timeseries", ...
        "MaxDataPoints", "inf", ...
        "Position", position);
end

function add_goto(model_name, block_name, tag, position)
    add_block("simulink/Signal Routing/Goto", model_name + "/" + block_name, ...
        "GotoTag", tag, ...
        "TagVisibility", "global", ...
        "Position", position);
end

function add_joint_display_subsystems(model_name)
    joint_labels = [
        "J1 spm1 z yaw", ...
        "J2 spm1 y pitch", ...
        "J3 spm1 x roll", ...
        "J4 spm2 z yaw", ...
        "J5 spm2 y pitch", ...
        "J6 spm2 x roll" ...
    ];
    block_names = [
        "J1_spm1_z_scopes", ...
        "J2_spm1_y_scopes", ...
        "J3_spm1_x_scopes", ...
        "J4_spm2_z_scopes", ...
        "J5_spm2_y_scopes", ...
        "J6_spm2_x_scopes" ...
    ];

    x0 = 60;
    y0 = 700;
    dx = 740;
    dy = 285;
    width = 650;
    height = 205;

    for joint_index = 1:6
        row = floor((joint_index - 1) / 3);
        col = mod(joint_index - 1, 3);
        position = [x0 + col * dx, y0 + row * dy, x0 + col * dx + width, y0 + row * dy + height];
        subsystem_path = model_name + "/" + block_names(joint_index);

        add_block("simulink/Ports & Subsystems/Subsystem", subsystem_path, ...
            "Position", position, ...
            "BackgroundColor", "lightBlue", ...
            "FontSize", 15, ...
            "FontWeight", "bold");
        Simulink.SubSystem.deleteContents(subsystem_path);
        set_param(subsystem_path, "NamePlacement", "normal");
        build_joint_display_subsystem(subsystem_path, joint_index, joint_labels(joint_index));
    end
end

function build_joint_display_subsystem(subsystem_path, joint_index, ~)

    angle_scope = subsystem_path + "/Angle rad";
    velocity_scope = subsystem_path + "/Velocity radps";
    torque_scope = subsystem_path + "/Torque Nm";

    add_block("simulink/Sinks/Scope", angle_scope, ...
        "NumInputPorts", "5", ...
        "Position", [760, 55, 1060, 190], ...
        "FontSize", 15);
    style_scope(angle_scope, "Angle response", "Angle (rad)", [120, 140, 980, 560]);
    add_block("simulink/Sinks/Scope", velocity_scope, ...
        "NumInputPorts", "4", ...
        "Position", [760, 245, 1060, 380], ...
        "FontSize", 15);
    style_scope(velocity_scope, "Velocity response", "Velocity (rad/s)", [160, 170, 980, 560]);
    add_block("simulink/Sinks/Scope", torque_scope, ...
        "NumInputPorts", "1", ...
        "Position", [760, 435, 1060, 540], ...
        "FontSize", 15);
    style_scope(torque_scope, "Torque command", "Torque (N*m)", [200, 200, 980, 520]);

    angle_tags = ["q_desired_vec", "q_target_old_vec", "q_actual_old_vec", "q_target_new_vec", "q_sim_new_vec"];
    angle_names = ["q_desired", "q_target_old", "q_actual_old", "q_target_new", "q_sim_new"];
    angle_legend_names = ["q desired", "old target", "old actual", "new target", "new sim"];
    for signal_index = 1:numel(angle_tags)
        add_from_demux(subsystem_path, angle_names(signal_index), angle_tags(signal_index), ...
            [55, 75 + (signal_index - 1) * 42, 205, 107 + (signal_index - 1) * 42], ...
            [290, 75 + (signal_index - 1) * 42, 322, 107 + (signal_index - 1) * 42]);
        add_named_line(subsystem_path, "Demux_" + angle_names(signal_index) + "/" + string(joint_index), ...
            "Angle rad/" + string(signal_index), angle_legend_names(signal_index));
    end

    velocity_tags = ["qdot_actual_old_vec", "qdot_cmd_old_vec", "qdot_sim_new_vec", "qdot_alloc_new_vec"];
    velocity_names = ["qdot_actual_old", "qdot_cmd_old", "qdot_sim_new", "qdot_alloc_new"];
    velocity_legend_names = ["old qdot actual", "old qdot cmd", "new qdot sim", "new qdot alloc"];
    for signal_index = 1:numel(velocity_tags)
        add_from_demux(subsystem_path, velocity_names(signal_index), velocity_tags(signal_index), ...
            [55, 270 + (signal_index - 1) * 42, 205, 302 + (signal_index - 1) * 42], ...
            [290, 270 + (signal_index - 1) * 42, 322, 302 + (signal_index - 1) * 42]);
        add_named_line(subsystem_path, "Demux_" + velocity_names(signal_index) + "/" + string(joint_index), ...
            "Velocity radps/" + string(signal_index), velocity_legend_names(signal_index));
    end

    add_from_demux(subsystem_path, "tau_sim_new", "tau_sim_new_vec", ...
        [55, 470, 205, 502], [290, 470, 322, 502]);
    add_named_line(subsystem_path, "Demux_tau_sim_new/" + string(joint_index), "Torque Nm/1", "new tau");

end

function demux_path = add_from_demux(subsystem_path, signal_name, tag, from_position, demux_position)
    from_path = subsystem_path + "/From_" + signal_name;
    demux_path = subsystem_path + "/Demux_" + signal_name;
    add_block("simulink/Signal Routing/From", from_path, ...
        "GotoTag", tag, ...
        "Position", from_position, ...
        "FontSize", 13);
    add_block("simulink/Signal Routing/Demux", demux_path, ...
        "Outputs", "6", ...
        "Position", demux_position, ...
        "FontSize", 13);
    add_line(subsystem_path, "From_" + signal_name + "/1", "Demux_" + signal_name + "/1", "autorouting", "on");
end

function add_named_line(system_path, source_port, destination_port, signal_name)
    line_handle = add_line(system_path, source_port, destination_port, "autorouting", "on");
    try
        set_param(line_handle, "Name", signal_name);
        set_param(line_handle, "FontSize", 13);
    catch
    end
end

function style_scope(scope_path, title_text, y_label, window_position)
    set_param(scope_path, ...
        "BackgroundColor", "white", ...
        "ForegroundColor", "black", ...
        "FontName", "Arial", ...
        "FontSize", 15, ...
        "ShowLegend", "on", ...
        "ShowGrid", "on");
    try
        scope_config = get_param(scope_path, "ScopeConfiguration");
        scope_config.Title = title_text;
        scope_config.YLabel = y_label;
        scope_config.ShowLegend = true;
        scope_config.ShowGrid = true;
        scope_config.MaximizeAxes = "On";
        scope_config.MinimizeControls = true;
        scope_config.AxesScaling = "Auto";
        scope_config.TimeAxisLabels = "Bottom";
        scope_config.ShowTimeAxisLabel = true;
        scope_config.PreserveColorsForCopyToClipboard = false;
        scope_config.Position = window_position;
    catch
    end
end

function style_blocks(model_name)
    all_blocks = find_system(model_name, "FindAll", "on", "Type", "Block");
    for block = reshape(all_blocks, 1, [])
        try
            set_param(block, "FontName", "Arial");
            set_param(block, "FontSize", 14);
        catch
        end
    end

    try
        set_param(model_name, "Location", [60, 60, 1880, 1040]);
        set_param(model_name, "ZoomFactor", "FitSystem");
    catch
    end

    color_blocks(model_name, ["q_desired", "q_target_old", "q_actual_old", "qdot_actual_old", "qdot_cmd_old"], "lightGreen");
    color_blocks(model_name, ["Clamp q target", "q error", "Kp", "Kd", "PD torque", "Torque saturation"], "lightBlue");
    color_blocks(model_name, ["qdot integrator", "qdot saturation", "q integrator", "q saturation", "qdot allocator LPF"], "yellow");
    color_blocks(model_name, ["q_target_new", "q_sim_new", "qdot_sim_new", "qdot_alloc_new", "tau_sim_new", "tau_saturation_flag_new"], "white");
end

function color_blocks(model_name, block_names, color)
    for block_name = block_names
        block_path = model_name + "/" + block_name;
        if getSimulinkBlockHandle(block_path) ~= -1
            try
                set_param(block_path, "BackgroundColor", color);
            catch
            end
        end
    end
end

function connect_blocks(model_name)
    add_line(model_name, "q_desired/1", "Clamp q target/1", "autorouting", "on");
    add_line(model_name, "Clamp q target/1", "q error/1", "autorouting", "on");
    add_line(model_name, "q saturation/1", "q error/2", "autorouting", "on");
    add_line(model_name, "q error/1", "Kp/1", "autorouting", "on");
    add_line(model_name, "Kp/1", "PD torque/1", "autorouting", "on");
    add_line(model_name, "qdot saturation/1", "Kd/1", "autorouting", "on");
    add_line(model_name, "Kd/1", "PD torque/2", "autorouting", "on");
    add_line(model_name, "PD torque/1", "Torque saturation/1", "autorouting", "on");
    add_line(model_name, "Torque saturation/1", "Acceleration numerator/1", "autorouting", "on");
    add_line(model_name, "qdot saturation/1", "B damping/1", "autorouting", "on");
    add_line(model_name, "B damping/1", "Acceleration numerator/2", "autorouting", "on");
    add_line(model_name, "Load torque/1", "Acceleration numerator/3", "autorouting", "on");
    add_line(model_name, "Acceleration numerator/1", "InvJ/1", "autorouting", "on");
    add_line(model_name, "InvJ/1", "qdot integrator/1", "autorouting", "on");
    add_line(model_name, "qdot integrator/1", "qdot saturation/1", "autorouting", "on");
    add_line(model_name, "qdot saturation/1", "q integrator/1", "autorouting", "on");
    add_line(model_name, "q integrator/1", "q saturation/1", "autorouting", "on");
    add_line(model_name, "qdot saturation/1", "qdot allocator LPF/1", "autorouting", "on");
    add_line(model_name, "Torque saturation/1", "Abs tau/1", "autorouting", "on");
    add_line(model_name, "Abs tau/1", "tau saturation flag/1", "autorouting", "on");

    add_line(model_name, "Clamp q target/1", "q_target_new/1", "autorouting", "on");
    add_line(model_name, "q saturation/1", "q_sim_new/1", "autorouting", "on");
    add_line(model_name, "qdot saturation/1", "qdot_sim_new/1", "autorouting", "on");
    add_line(model_name, "qdot allocator LPF/1", "qdot_alloc_new/1", "autorouting", "on");
    add_line(model_name, "Torque saturation/1", "tau_sim_new/1", "autorouting", "on");
    add_line(model_name, "tau saturation flag/1", "tau_saturation_flag_new/1", "autorouting", "on");

    add_line(model_name, "q_desired/1", "goto_q_desired/1", "autorouting", "on");
    add_line(model_name, "q_target_old/1", "goto_q_target_old/1", "autorouting", "on");
    add_line(model_name, "q_actual_old/1", "goto_q_actual_old/1", "autorouting", "on");
    add_line(model_name, "qdot_actual_old/1", "goto_qdot_actual_old/1", "autorouting", "on");
    add_line(model_name, "qdot_cmd_old/1", "goto_qdot_cmd_old/1", "autorouting", "on");
    add_line(model_name, "Clamp q target/1", "goto_q_target_new/1", "autorouting", "on");
    add_line(model_name, "q saturation/1", "goto_q_sim_new/1", "autorouting", "on");
    add_line(model_name, "qdot saturation/1", "goto_qdot_sim_new/1", "autorouting", "on");
    add_line(model_name, "qdot allocator LPF/1", "goto_qdot_alloc_new/1", "autorouting", "on");
    add_line(model_name, "Torque saturation/1", "goto_tau_sim_new/1", "autorouting", "on");
end
