[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Complete Car RL Training"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description="Isaac Lab training project for the articulated complete-car robot"
repository = "https://github.com/isaac-sim/IsaacLab.git"
keywords = ["isaaclab", "reinforcement-learning", "robotics"]

[dependencies]
"isaaclab" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "complete_car_rl_training"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
